$script_mysql = <<-SCRIPT
apt-get update && \
apt-get install -y mysql-server-5.7 && \
mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

$script_ansible = <<-SCRIPT
apt-get update &&  \
apt-get install -y software-properties-common && \
apt-add-repository --yes --update ppa:ansible/ansible && \
apt-get install -y ansible
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "mysqldb" do |mysql|
    mysql.vm.network "public_network", ip: "192.168.0.200", 
      bridge: "Qualcomm Atheros QCA9377 Wireless Network Adapter"

    mysql.vm.provision "shell", inline: "cat /configs/minha_chave.pub >> .ssh/authorized_keys"
    mysql.vm.provision "shell", inline: $script_mysql
    mysql.vm.provision "shell", inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
    mysql.vm.provision "shell", inline: "service mysql restart"

    mysql.vm.synced_folder "./configs", "/configs"
    mysql.vm.synced_folder ".", "/vagrant", disabled: true
  end

  config.vm.define "phpweb" do |phpweb|
    phpweb.vm.network "forwarded_port", guest: 8888, host: 8888
    phpweb.vm.network "public_network", ip: "192.168.0.201", 
      bridge: "Qualcomm Atheros QCA9377 Wireless Network Adapter"

    phpweb.vm.provision "shell", inline: "apt-get update && apt-get install -y puppet"
    
    phpweb.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "./configs/manifests"
      puppet.manifest_file = "phpweb.pp"
    end  
  end

  config.vm.define "mysqlserver" do |mysqlserver|
    mysqlserver.vm.network "public_network", ip: "192.168.0.202", 
      bridge: "Qualcomm Atheros QCA9377 Wireless Network Adapter"

    mysqlserver.vm.provision "shell", inline: "cat /vagrant/configs/minha_chave.pub >> .ssh/authorized_keys"
  end
  
  config.vm.define "ansible" do |ansible|
    ansible.vm.network "public_network", ip: "192.168.0.203", 
      bridge: "Qualcomm Atheros QCA9377 Wireless Network Adapter"

    ansible.vm.provision "shell", inline: $script_ansible

    ansible.vm.provision "shell",
      inline: "cp /vagrant/minha_chave /home/vagrant/minha_chave && \
               chmod 600 /home/vagrant/minha_chave && \
               chown vagrant:vagrant /home/vagrant/minha_chave"

    ansible.vm.provision "shell",
      inline: "ansible-playbook -i /vagrant/configs/ansible/hosts \
               /vagrant/configs/ansible/playbook.yml"
  end
end